apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{- include "care.name" . | nindent 4 }}-cmsadmin
  labels:
    {{- include "cmsadmin.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount.cmsadmin }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cmsadmin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cmsadmin.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "care.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "care.name" . }}-cmsadmin
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.back.image }}:{{ .Values.back.imageTag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.back.imagePullPolicy }}
          env:
            - name: MODE
              value: {{ .Values.MODE }}
            {{- if .Values.proxyBalancer.enabled }}
            - name: https_proxy
              value: http://proxybalancer:3127
            {{- end }}
            {{- range $back_var, $back_val := .Values.back.env }}
            - name: {{ $back_var }}
              value: "{{ $back_val }}"
            {{- end }}
          ports:
            - name: http-cmsadmin
              containerPort: {{ add 4 (.Values.back.port) }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ add 4 (.Values.back.port) }}
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /admin/
              port: {{ add 4 (.Values.back.port) }}
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 10
          command: ["uwsgi"]
          args:
            - "--http-socket=0.0.0.0:{{ add 4 (.Values.back.port) }}"
            - "--processes=10"
            - "--wsgi-file=admin.py"
            - "--master"
            - "--need-app"
            - "--callable=app"
            - "--die-on-term"
            - "--enable-threads"
          resources:
            {{- toYaml .Values.resources.cmsadmin | nindent 12 }}
          volumeMounts:
            - name: ca-certificates
              mountPath: /etc/ssl/certs/ca-certificates.crt
              subPath: ca-certificates.crt
            - name: ca-certificates
              mountPath: /opt/venv/lib/python3.8/site-packages/certifi/cacert.pem
              subPath: ca-certificates.crt
      volumes:
        - name: ca-certificates
          configMap:
            name: ca-cert
            defaultMode: 420
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
