apiVersion: v1
kind: Service
metadata:
  name: {{- include "care.name" . | nindent 4 }}-back
  labels:
    {{- include "back.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.back.type }}
  ports:
    - port: {{ .Values.service.back.port }}
      targetPort: {{ .Values.back.port }}
      protocol: TCP
      name: http-back
  selector:
    {{- include "back.selectorLabels" . | nindent 4 }}
